description: This is a template researchers can walk away with and create their own Portfolio.
datelastupdated: Nov 2021
fullnameofperson: Amanda Miotto
selfIdentification: eResearch Analyst and lover of Science and IT
colour1: "#274c77"  # sidebar background 
colour2: "#a3cef1"  # colour of name and desc
colour3: "#a3cef1"  # colour of Menu links
colour4: "#d4dfc7" # trying to be background colour - still experimenting 
colour5: "#e7ecef" # menu link colour when hover
